using System;
using System.Collections.Generic;
using System.Text;
using ElementFlash.Model;

namespace ElementFlash.Services
{
    public class ElementService
    {
        private readonly List<Model.Element> elements =
        [
            new() { AtomicNumber = 1, Symbol = "H",  Name = "水素" },
            new() { AtomicNumber = 2, Symbol = "He", Name = "ヘリウム" },
            new() { AtomicNumber = 3, Symbol = "Li", Name = "リチウム" },
            new() { AtomicNumber = 4, Symbol = "Be", Name = "ベリリウム" },
            new() { AtomicNumber = 5, Symbol = "B",  Name = "ホウ素" },
            new() { AtomicNumber = 6, Symbol = "C",  Name = "炭素" },
            new() { AtomicNumber = 7, Symbol = "N",  Name = "窒素" },
            new() { AtomicNumber = 8, Symbol = "O",  Name = "酸素" },
            new() { AtomicNumber = 9, Symbol = "F",  Name = "フッ素" },
            new() { AtomicNumber = 10, Symbol = "Ne", Name = "ネオン" },
            new() { AtomicNumber = 11, Symbol = "Na", Name = "ナトリウム" },
            new() { AtomicNumber = 12, Symbol = "Mg", Name = "マグネシウム" },
            new() { AtomicNumber = 13, Symbol = "Al", Name = "アルミニウム" },
            new() { AtomicNumber = 14, Symbol = "Si", Name = "ケイ素" },
            new() { AtomicNumber = 15, Symbol = "P",  Name = "リン" },
            new() { AtomicNumber = 16, Symbol = "S",  Name = "硫黄" },
            new() { AtomicNumber = 17, Symbol = "Cl", Name = "塩素" },
            new() { AtomicNumber = 18, Symbol = "Ar", Name = "アルゴン" },
            new() { AtomicNumber = 19, Symbol = "K",  Name = "カリウム" },
            new() { AtomicNumber = 20, Symbol = "Ca", Name = "カルシウム" },
            new() { AtomicNumber = 21, Symbol = "Sc", Name = "スカンジウム" },
            new() { AtomicNumber = 22, Symbol = "Ti", Name = "チタン" },
            new() { AtomicNumber = 23, Symbol = "V",  Name = "バナジウム" },
            new() { AtomicNumber = 24, Symbol = "Cr", Name = "クロム" },
            new() { AtomicNumber = 25, Symbol = "Mn", Name = "マンガン" },
            new() { AtomicNumber = 26, Symbol = "Fe", Name = "鉄" },
            new() { AtomicNumber = 27, Symbol = "Co", Name = "コバルト" },
            new() { AtomicNumber = 28, Symbol = "Ni", Name = "ニッケル" },
            new() { AtomicNumber = 29, Symbol = "Cu", Name = "銅" },
            new() { AtomicNumber = 30, Symbol = "Zn", Name = "亜鉛" },
            new() { AtomicNumber = 31, Symbol = "Ga", Name = "ガリウム" },
            new() { AtomicNumber = 32, Symbol = "Ge", Name = "ゲルマニウム" },
            new() { AtomicNumber = 33, Symbol = "As", Name = "ヒ素" },
            new() { AtomicNumber = 34, Symbol = "Se", Name = "セレン" },
            new() { AtomicNumber = 35, Symbol = "Br", Name = "臭素" },
            new() { AtomicNumber = 36, Symbol = "Kr", Name = "クリプトン" },
            new() { AtomicNumber = 37, Symbol = "Rb", Name = "ルビジウム" },
            new() { AtomicNumber = 38, Symbol = "Sr", Name = "ストロンチウム" },
            new() { AtomicNumber = 39, Symbol = "Y",  Name = "イットリウム" },
            new() { AtomicNumber = 40, Symbol = "Zr", Name = "ジルコニウム" },
            new() { AtomicNumber = 41, Symbol = "Nb", Name = "ニオブ" },
            new() { AtomicNumber = 42, Symbol = "Mo", Name = "モリブデン" },
            new() { AtomicNumber = 43, Symbol = "Tc", Name = "テクネチウム" },
            new() { AtomicNumber = 44, Symbol = "Ru", Name = "ルテニウム" },
            new() { AtomicNumber = 45, Symbol = "Rh", Name = "ロジウム" },
            new() { AtomicNumber = 46, Symbol = "Pd", Name = "パラジウム" },
            new() { AtomicNumber = 47, Symbol = "Ag", Name = "銀" },
            new() { AtomicNumber = 48, Symbol = "Cd", Name = "カドミウム" },
            new() { AtomicNumber = 49, Symbol = "In", Name = "インジウム" },
            new() { AtomicNumber = 50, Symbol = "Sn", Name = "スズ" },
            new() { AtomicNumber = 51, Symbol = "Sb", Name = "アンチモン" },
            new() { AtomicNumber = 52, Symbol = "Te", Name = "テルル" },
            new() { AtomicNumber = 53, Symbol = "I",  Name = "ヨウ素" },
            new() { AtomicNumber = 54, Symbol = "Xe", Name = "キセノン" },
            new() { AtomicNumber = 55, Symbol = "Cs", Name = "セシウム" },
            new() { AtomicNumber = 56, Symbol = "Ba", Name = "バリウム" },
            new() { AtomicNumber = 57, Symbol = "La", Name = "ランタン" },
            new() { AtomicNumber = 58, Symbol = "Ce", Name = "セリウム" },
            new() { AtomicNumber = 59, Symbol = "Pr", Name = "プラセオジム" },
            new() { AtomicNumber = 60, Symbol = "Nd", Name = "ネオジム" },
            new() { AtomicNumber = 61, Symbol = "Pm", Name = "プロメチウム" },
            new() { AtomicNumber = 62, Symbol = "Sm", Name = "サマリウム" },
            new() { AtomicNumber = 63, Symbol = "Eu", Name = "ユウロピウム" },
            new() { AtomicNumber = 64, Symbol = "Gd", Name = "ガドリニウム" },
            new() { AtomicNumber = 65, Symbol = "Tb", Name = "テルビウム" },
            new() { AtomicNumber = 66, Symbol = "Dy", Name = "ジスプロシウム" },
            new() { AtomicNumber = 67, Symbol = "Ho", Name = "ホルミウム" },
            new() { AtomicNumber = 68, Symbol = "Er", Name = "エルビウム" },
            new() { AtomicNumber = 69, Symbol = "Tm", Name = "ツリウム" },
            new() { AtomicNumber = 70, Symbol = "Yb", Name = "イッテルビウム" },
            new() { AtomicNumber = 71, Symbol = "Lu", Name = "ルテチウム" },
            new() { AtomicNumber = 72, Symbol = "Hf", Name = "ハフニウム" },
            new() { AtomicNumber = 73, Symbol = "Ta", Name = "タンタル" },
            new() { AtomicNumber = 74, Symbol = "W",  Name = "タングステン" },
            new() { AtomicNumber = 75, Symbol = "Re", Name = "レニウム" },
            new() { AtomicNumber = 76, Symbol = "Os", Name = "オスミウム" },
            new() { AtomicNumber = 77, Symbol = "Ir", Name = "イリジウム" },
            new() { AtomicNumber = 78, Symbol = "Pt", Name = "白金" },
            new() { AtomicNumber = 79, Symbol = "Au", Name = "金" },
            new() { AtomicNumber = 80, Symbol = "Hg", Name = "水銀" },
            new() { AtomicNumber = 81, Symbol = "Tl", Name = "タリウム" },
            new() { AtomicNumber = 82, Symbol = "Pb", Name = "鉛" },
            new() { AtomicNumber = 83, Symbol = "Bi", Name = "ビスマス" },
            new() { AtomicNumber = 84, Symbol = "Po", Name = "ポロニウム" },
            new() { AtomicNumber = 85, Symbol = "At", Name = "アスタチン" },
            new() { AtomicNumber = 86, Symbol = "Rn", Name = "ラドン" },
            new() { AtomicNumber = 87, Symbol = "Fr", Name = "フランシウム" },
            new() { AtomicNumber = 88, Symbol = "Ra", Name = "ラジウム" },
            new() { AtomicNumber = 89, Symbol = "Ac", Name = "アクチニウム" },
            new() { AtomicNumber = 90, Symbol = "Th", Name = "トリウム" },
            new() { AtomicNumber = 91, Symbol = "Pa", Name = "プロトアクチニウム" },
            new() { AtomicNumber = 92, Symbol = "U",  Name = "ウラン" },
            new() { AtomicNumber = 93, Symbol = "Np", Name = "ネプツニウム" },
            new() { AtomicNumber = 94, Symbol = "Pu", Name = "プルトニウム" },
            new() { AtomicNumber = 95, Symbol = "Am", Name = "アメリシウム" },
            new() { AtomicNumber = 96, Symbol = "Cm", Name = "キュリウム" },
            new() { AtomicNumber = 97, Symbol = "Bk", Name = "バークリウム" },
            new() { AtomicNumber = 98, Symbol = "Cf", Name = "カリホルニウム" },
            new() { AtomicNumber = 99, Symbol = "Es", Name = "アインスタイニウム" },
            new() { AtomicNumber = 100, Symbol = "Fm", Name = "フェルミウム" },
            new() { AtomicNumber = 101, Symbol = "Md", Name = "メンデレビウム" },
            new() { AtomicNumber = 102, Symbol = "No", Name = "ノーベリウム" },
            new() { AtomicNumber = 103, Symbol = "Lr", Name = "ローレンシウム" },
            new() { AtomicNumber = 104, Symbol = "Rf", Name = "ラザホージウム" },
            new() { AtomicNumber = 105, Symbol = "Db", Name = "ドブニウム" },
            new() { AtomicNumber = 106, Symbol = "Sg", Name = "シーボーギウム" },
            new() { AtomicNumber = 107, Symbol = "Bh", Name = "ボーリウム" },
            new() { AtomicNumber = 108, Symbol = "Hs", Name = "ハッシウム" },
            new() { AtomicNumber = 109, Symbol = "Mt", Name = "マイトネリウム" },
            new() { AtomicNumber = 110, Symbol = "Ds", Name = "ダームスタチウム" },
            new() { AtomicNumber = 111, Symbol = "Rg", Name = "レントゲニウム" },
            new() { AtomicNumber = 112, Symbol = "Cn", Name = "コペルニシウム" },
            new() { AtomicNumber = 113, Symbol = "Nh", Name = "ニホニウム" },
            new() { AtomicNumber = 114, Symbol = "Fl", Name = "フレロビウム" },
            new() { AtomicNumber = 115, Symbol = "Mc", Name = "モスコビウム" },
            new() { AtomicNumber = 116, Symbol = "Lv", Name = "リバモリウム" },
            new() { AtomicNumber = 117, Symbol = "Ts", Name = "テネシン" },
            new() { AtomicNumber = 118, Symbol = "Og", Name = "オガネソン" },
        ];
        public Model.Element Get(int n) { return elements[n]; }
        public List<Model.Element> GetAll() => elements;
    }
}
